services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ans_api_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST:?Variável não definida no .env}
      DB_PORT: ${DB_PORT:?Variável não definida no .env}
      DB_NAME: ${DB_NAME:?Variável não definida no .env}
      DB_USER: ${DB_USER:?Variável não definida no .env}
      DB_PASSWORD: ${DB_PASSWORD:?Variável não definida no .env}
      API_HOST: ${API_HOST:?Variável não definida no .env}
      API_PORT: ${API_PORT:?Variável não definida no .env}
    volumes:
      - ./app:/app/app:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - ans_network

networks:
  ans_network:
    name: ans_network
    driver: bridge
